# Generated by Django 2.1.2 on 2020-06-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200609_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupuser',
            old_name='group',
            new_name='group_id',
        ),
        migrations.RenameField(
            model_name='groupuser',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='event',
            name='arquivado',
            field=models.BooleanField(default=True),
        ),
    ]
